flyway.url=jdbc:postgresql://ep-royal-recipe-a1mk03y3-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
flyway.user=neondb_owner
flyway.password=npg_DLzl3Xi0xWsd
flyway.schemas=public
flyway.defaultSchema=public
flyway.locations=filesystem:src/main/resources/db/migration
